import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import  "./page"
export const metadata = {
  title: "Portafolio",
  description: "Generated by create next app",
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    
  );

  
}
